/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ScheduleRouteImport } from './routes/schedule'
import { Route as JenniferFennerRouteImport } from './routes/jennifer-fenner'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as ConsultationRouteImport } from './routes/consultation'
import { Route as IndexRouteImport } from './routes/index'

const ScheduleRoute = ScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => rootRouteImport,
} as any)
const JenniferFennerRoute = JenniferFennerRouteImport.update({
  id: '/jennifer-fenner',
  path: '/jennifer-fenner',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const ConsultationRoute = ConsultationRouteImport.update({
  id: '/consultation',
  path: '/consultation',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/faq': typeof FaqRoute
  '/jennifer-fenner': typeof JenniferFennerRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/faq': typeof FaqRoute
  '/jennifer-fenner': typeof JenniferFennerRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/consultation': typeof ConsultationRoute
  '/faq': typeof FaqRoute
  '/jennifer-fenner': typeof JenniferFennerRoute
  '/schedule': typeof ScheduleRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/consultation' | '/faq' | '/jennifer-fenner' | '/schedule'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/consultation' | '/faq' | '/jennifer-fenner' | '/schedule'
  id:
    | '__root__'
    | '/'
    | '/consultation'
    | '/faq'
    | '/jennifer-fenner'
    | '/schedule'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ConsultationRoute: typeof ConsultationRoute
  FaqRoute: typeof FaqRoute
  JenniferFennerRoute: typeof JenniferFennerRoute
  ScheduleRoute: typeof ScheduleRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/schedule': {
      id: '/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof ScheduleRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jennifer-fenner': {
      id: '/jennifer-fenner'
      path: '/jennifer-fenner'
      fullPath: '/jennifer-fenner'
      preLoaderRoute: typeof JenniferFennerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/consultation': {
      id: '/consultation'
      path: '/consultation'
      fullPath: '/consultation'
      preLoaderRoute: typeof ConsultationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ConsultationRoute: ConsultationRoute,
  FaqRoute: FaqRoute,
  JenniferFennerRoute: JenniferFennerRoute,
  ScheduleRoute: ScheduleRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
